server:
  port: 8080
  servlet:
    context-path: /identity

client:
  port: 5173

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.mpddbzkmroumgazdwomn&password=Ducdung789!
    username: postgres
    password: Ducdung789!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tourxuyenviet2025@gmail.com
    password: agbv ddct eqzw jwko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: "x5N/IYQDk/BvPC2XWv7xE2TdU2YlZsewgbUOvN3/m71lrjo74knXkebs4jSmEjjQ"
  valid-duration: 3000 # in seconds
  refreshable-duration: 72000 # in seconds
  logging:
    level:
      org.springframework: DEBUG
      com.devteria: DEBUG

#cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_NAME:deq6qkrq5}
  api-key: ${CLOUDINARY_KEY:351231857363369}
  api-secret: ${CLOUDINARY_SECRET:v3FDad5YAriUwrH6NT0LVneav3k}

app:
  verificationCodeExpiry: 5 #in minutes
  passwordResetCodeExpiry: 3 #in minutes